name: .NET Core - Build and Deploy

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: api-sds-cv-guard
  DOTNET_VERSION: '8.x'
  PROJECT_PATH: './Cv.Guard.Api/Cv.Guard.Api.csproj'
  TEST_PROJECT_PATH: './Cv.Guard.Tests/Cv.Guard.Tests.csproj'
  PUBLISH_PATH: './publish'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.PROJECT_PATH }}
          dotnet restore ${{ env.TEST_PROJECT_PATH }}
        
      - name: Validate appsettings.json
        run: |
          if (!(Test-Path './Cv.Guard.Api/appsettings.json')) {
            Write-Host "Error: appsettings.json not found!"
            exit 1
          }
        shell: pwsh

      - name: Configure appsettings.json
        run: |
          $config = Get-Content ./Cv.Guard.Api/appsettings.json | ConvertFrom-Json
          $config.ConnectionStrings.DefaultConnection = "${{ secrets.AZURE_SQL_SERVER_CONNECTION_STRING }}"
          $config.AzureBlob.ConnectionString = "${{ secrets.AZURE_FILE_STORAGE_CONNECTION_STRING }}"
          $config.AzureBlob.Name = "${{ secrets.AZURE_FILE_STORAGE_CONTAINER_NAME }}"
          $config.Postmark.Key = "${{ secrets.POSTMARK_API_KEY }}"
          $config.IpStack.ApiKey = "${{ secrets.IPSTACK_API_KEY }}"
          $config | ConvertTo-Json -Depth 10 | Set-Content ./Cv.Guard.Api/appsettings.json
        shell: pwsh

      - name: Build API
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

      - name: Build Tests
        run: dotnet build ${{ env.TEST_PROJECT_PATH }} --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} --configuration Release --no-build

      - name: Publish API
        run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_PATH }} --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.PUBLISH_PATH }}
          retention-days: 1

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .