name: Build, Test And Deploy Cv Guard Api
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [develop]
env:
  APP_SOLUTION_FILE: './CV-Guard-Api.sln'
  APP_API_PROJECT: './Cv.Guard.Api/Cv.Guard.Api.csproj'
  PUBLISH_PATH: './publish'
  DOTNET_VER: '8.x'
  AZURE_WEBAPP_NAME: api-sds-cv-guard

jobs:
  restore-and-build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4 
        with:
          dotnet-version: '8.0.x'           
      
      - name: Cache Nuget packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/packages.config', '**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      
      - name: Cache build outputs
        uses: actions/cache@v3
        with:
          path: "**/bin\n**/obj"
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-
      
      - name: Restore dependencies
        run: dotnet restore ${{env.APP_SOLUTION_FILE}}
      
      - name: Build
        run: dotnet build --configuration Release ${{env.APP_SOLUTION_FILE}}
      
      - name: Publish
        run: dotnet publish ${{env.APP_API_PROJECT}} -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
  
  integration-test:
    if: github.event.action != 'closed' || github.event.pull_request.merged != true
    runs-on: windows-latest
    needs: [restore-and-build]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Test
        run: dotnet test ${{env.APP_SOLUTION_FILE}} --no-build --verbosity normal
  
  deploy:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: windows-latest
    needs: [integration-test]
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F40672CF50DD4CC08C0A3E4452ACCF52 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C4C46E97AA6C411CBF4DC419E25F798A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_17F66040F75C4F57A1CFD5926454B3C4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cv-guard-api'
          slot-name: 'Production'
          package: .